### ISSUE TITLE
Create Toolbar

### ISSUE THREAD

**Issue by TrizML** [codecampleipzig/communic#42]
## Create  Toolbar
- As a **Regular User**
- I want **to see a fixed toolbar**
- So that **I can go home, create a new project, see my username, my thumbnails and logout.**

## Related Stories:
 - [x] Home Button #44
 - [x] New Project Button  #45
 - [x] User Profile #46
 - [x] Logout Button #43 
 - [x] Routing for toolbar #55

## Tasks

- [x] Design

- [x] Test Components:

     - [x] Toolbar as a whole
          - [x] Home Button:
               - [x] Is it there?
               - [x] Click event
          - [x] Is Project Action there?
          - [x] Is User Control there?

     - [x] Project Action:
          - [x] Click event
          - [x] One way binding Project Name

     - [x] User Control
          - [x] One way binding Username
          - [x] Is the Logout there?
          - [x] Click event for Logout #43 
          - [x] Is the User Thumbnail there?
          - [x] One way binding User Thumbnail

- [x] Documentation

**Comment by TrizML** [comment]
Implemented
