### ISSUE TITLE
Create 'My Projects' Section

### ISSUE THREAD

**Issue by TrizML** [codecampleipzig/communic#50]
## My Projects Section
- As a **user**
- I want **to see a section with my projects.**
- So that **I can see list all the projects I joined.**

## Related Issues
- [x] Create My Projects Wrapper #47
- [x] Create Projects Display Cards #48
- [x] Show all projects from an user #49 

## Tasks
- [x] Design
     - [x] Card
     - [x] Section

- [ ] Test Components:
     - [ ] Image
     - [ ] Title
     - [ ] Description
     - [ ] Read More
- [ ] Documentation

**Comment by TrizML** [comment]
Implemented
