### ISSUE TITLE
Create Explore Projects Section

### ISSUE THREAD

**Issue by TrizML** [codecampleipzig/communic#54]
## Explore Projects Section
- As a **user**
- I want **to have a section under my projects**
- So that **I can explore the projects and see if I can join them.**

## Related Issues
- [x] Create Explore Projects Wrapper #51
- [x] Create Explore Projects Display Cards #52
- [x] Show all projects to be explored #53

## Tasks
- [x] Design
     - [x] Card
     - [x] Section

- [ ] Test Components:
     - [ ] Image
     - [ ] Title
     - [ ] Description
     - [ ] Read More
- [ ] Documentation

**Comment by TrizML** [comment]
Testing will be postpone

**Comment by TrizML** [comment]
Implemented
