### ISSUE TITLE
New Project Database

### ISSUE THREAD

**Issue by iko95** [codecampleipzig/communic#95]
**User Storys**
- As a user
- i want to save a new project
- so it  will be displayed in "my projects" and i can enter it from there

- As a developer
- i want to know, if the join now button fetches all the data from the form and checks them with the users in the database
- so i can work with the database and user profiles

**Acceptance Criteria**
- [ ] the "Sign In" button needs to fetch the data from the form and return them inside an object
- [ ] the object needs to be saved in a service and checked with the database
- [ ] True of False needs to be returned

**Tasks:**
- [ ] Testing
- [ ] Documentation
