### ISSUE TITLE
Adapt Toolbar to Mobile First Approach

### ISSUE THREAD

**Issue by NicolasAranedaHinrichs** [codecampleipzig/communic#99]
## Change Username and Thumbnail for Logged User
- As as **user**
- I want **see the toolbar adapted to my smartphone**
- so that **I can interact clearly with each of its features.**

**Acceptance Criteria**
- [ ] toolbar should float over body content while scrolling,
- [ ] username, thumbnail and logout shouldn't cram up, and
- [ ] "Start a New Project" button should turn into "+" sign after home .

**Tasks:**
- [ ] Testing
- [ ] Documentation
